const CFG = window.FALTAH_CONFIG || {};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const defaultStore=JSON.parse(localStorage.getItem('faltah5')||'{}');
let store=Object.keys(defaultStore).length?defaultStore:{settings:{knowledgeBaseUrl:CFG.knowledgeBaseUrl||'https://msharyx99.github.io/FALTAH-Knowledge/',mediaBaseUrl:CFG.mediaBaseUrl||'https://msharyx99.github.io/FALTAH-Media/'},brand:{brandName:'FALTAH Enterprise',motto:'Learn • Apply • Excel',character:'characters/faltah-main.png',appIcon:'icons/faltah-app-icon.png',icons:{}},equipment:[],lessons:[]};
store.settings ||= {knowledgeBaseUrl:CFG.knowledgeBaseUrl||'',mediaBaseUrl:CFG.mediaBaseUrl||''}; store.brand ||= {}; store.brand.icons ||= {};
function save(){localStorage.setItem('faltah5',JSON.stringify(store));render()}
loginBtn.onclick=()=>{if(pw.value==='faltah'){login.classList.add('hidden');panel.classList.remove('hidden');render()}else alert('Wrong password')};
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('.tab').forEach(t=>t.classList.remove('active'));$$('[data-tab]').forEach(x=>x.classList.remove('active'));$("#"+b.dataset.tab).classList.add('active');b.classList.add('active')});
function render(){cmsName.value=store.brand.brandName||'';cmsMotto.value=store.brand.motto||'';cmsCharacter.value=store.brand.character||'';cmsAppIcon.value=store.brand.appIcon||'';knowledgeUrl.value=store.settings.knowledgeBaseUrl||'';mediaUrl.value=store.settings.mediaBaseUrl||'';let iconKeys=['dashboard','equipment','academy','library','assistant','challenges','analytics','settings','search'];iconFields.innerHTML=iconKeys.map(k=>`<label>${k}<input data-icon="${k}" value="${(store.brand.icons||{})[k]||''}" placeholder="Paste SVG or URL or emoji"></label>`).join('');eqList.innerHTML=store.equipment.map(e=>`<div class="row"><span>${e.icon||''} <b>${e.name}</b> - ${e.cat}</span><button onclick="editEq('${e.name.replaceAll("'","\\'")}')">Edit</button></div>`).join('');leList.innerHTML=store.lessons.map(l=>`<div class="row"><span><b>${l.title}</b> - ${l.eq}</span><button onclick="editLesson('${l.title.replaceAll("'","\\'")}')">Edit</button></div>`).join('');exportBox.value=JSON.stringify(store,null,2)}
saveBrand.onclick=()=>{store.brand.brandName=cmsName.value;store.brand.motto=cmsMotto.value;store.brand.character=cmsCharacter.value;store.brand.appIcon=cmsAppIcon.value;save()};
saveSettings.onclick=()=>{store.settings.knowledgeBaseUrl=knowledgeUrl.value;store.settings.mediaBaseUrl=mediaUrl.value;save()};
saveIcons.onclick=()=>{$$('[data-icon]').forEach(i=>store.brand.icons[i.dataset.icon]=i.value);save()};
addEq.onclick=()=>{let e={name:eqName.value,cat:eqCat.value,icon:eqIcon.value,desc:eqDesc.value};let idx=store.equipment.findIndex(x=>x.name===e.name);if(idx>=0)store.equipment[idx]=e;else store.equipment.push(e);eqName.value=eqCat.value=eqIcon.value=eqDesc.value='';save()};
window.editEq=n=>{let e=store.equipment.find(x=>x.name===n);eqName.value=e.name;eqCat.value=e.cat;eqIcon.value=e.icon;eqDesc.value=e.desc};
addLesson.onclick=()=>{let l={title:leTitle.value,eq:leEq.value,video:leVideo.value,doc:leDoc.value,summary:leSummary.value,keys:leKeys.value};let idx=store.lessons.findIndex(x=>x.title===l.title);if(idx>=0)store.lessons[idx]=l;else store.lessons.push(l);leTitle.value=leEq.value=leVideo.value=leDoc.value=leSummary.value=leKeys.value='';save()};
window.editLesson=t=>{let l=store.lessons.find(x=>x.title===t);leTitle.value=l.title;leEq.value=l.eq;leVideo.value=l.video;leDoc.value=l.doc;leSummary.value=l.summary;leKeys.value=l.keys};
downloadJson.onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(store,null,2)],{type:'application/json'}));a.download='content.json';a.click()};
render();
