import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Home,Network,Library,Brain,MoreHorizontal,Search,Lock,Play,ChevronDown,ChevronRight,Settings}from'lucide-react';import'./style.css';
const cats=[{n:'Static Equipment',c:'static',items:['Pressure Vessels','Separators','Heat Exchangers','Tanks','Filters','Reactors']},{n:'Rotating Equipment',c:'rotating',items:['Centrifugal Pumps','Compressors','Motors','Gearboxes','Mechanical Seals','Lubrication Systems']},{n:'Valves',c:'valves',items:['Gate Valve','Globe Valve','Ball Valve','Control Valve','Pressure Relief Valve','Solenoid Valve']}];
const coming=['Instrumentation & Control','Electrical Systems','Piping Systems','Utility Systems'];
const vids=['Centrifugal Pump Principles of Operation','Pump Cavitation Causes & Prevention','Pressure Relief Valve Operation','Heat Exchanger Function','Three Phase Separator Basics','Control Valve Working Principle'];
function App(){const[page,setPage]=useState('home');const[admin,setAdmin]=useState(false);const[pw,setPw]=useState('');return <div className="app"><main>{page==='home'&&<HomePage setPage={setPage}/>} {page==='tree'&&<Tree/>}{page==='library'&&<LibraryPage/>}{page==='ai'&&<AI/>}{page==='more'&&<More admin={admin} setAdmin={setAdmin} pw={pw} setPw={setPw}/>}</main><nav className="bottom"><button onClick={()=>setPage('home')} className={page==='home'?'on':''}><Home/>Home</button><button onClick={()=>setPage('tree')} className={page==='tree'?'on':''}><Network/>Tree</button><button onClick={()=>setPage('library')} className={page==='library'?'on':''}><Library/>Library</button><button onClick={()=>setPage('ai')} className={page==='ai'?'on':''}><Brain/>AI</button><button onClick={()=>setPage('more')} className={page==='more'?'on':''}><MoreHorizontal/>More</button></nav></div>}
function Header(){return <div className="top"><div className="brand"><span className="bolt">⚡</span><b>FALTAH</b><em>ENTERPRISE</em></div><div className="avatar">A</div></div>}
function HomePage({setPage}){return <section className="screen"><Header/><div className="hero"><div className="tag">DIGITAL ENGINEERING PLATFORM</div><h1>Welcome to <span>FALTAH</span><br/>Enterprise</h1><p className="sub">Search • Learn • Apply • Excel</p><ProcessArt/><SearchBox/><button className="primary" onClick={()=>setPage('tree')}>Explore Knowledge Tree</button><div className="actions"><button onClick={()=>setPage('library')}>Knowledge Library</button><button onClick={()=>setPage('ai')}>Ask FALTAH AI</button></div></div><div className="stats"><div><b>248</b><small>Equipment Items</small></div><div><b>3,210</b><small>Engineering Videos</small></div></div><h3>Featured Resources</h3><div className="videos">{vids.slice(0,4).map(v=><Video key={v} t={v}/>)}</div></section>}
function ProcessArt(){return <div className="plant"><div className="flow"></div><div className="vessel v1">V-101</div><div className="vessel v2">V-201</div><div className="pump">P-101</div><div className="valve">FV</div><div className="flare"><i></i></div></div>}
function SearchBox(){return <div className="search"><Search size={18}/><span>Search equipment, videos, failures, standards...</span></div>}
function Tree(){const[open,setOpen]=useState('Rotating Equipment');return <section className="screen"><Header/><SearchBox/><h2>Knowledge Tree</h2><div className="root">FALTAH Enterprise<br/><small>Digital Engineering Knowledge Root</small></div>{cats.map(c=><div className="node" onClick={()=>setOpen(open===c.n?'':c.n)}><div><b>{c.n}</b><small>{c.items.length} equipment types</small></div>{open===c.n?<ChevronDown/>:<ChevronRight/>}{open===c.n&&<ul>{c.items.map(i=><li>{i}</li>)}</ul>}</div>)}<h4>Coming Soon</h4>{coming.map(c=><div className="locked"><Lock size={15}/>{c}<small>Coming Soon</small></div>)}</section>}
function LibraryPage(){return <section className="screen"><Header/><SearchBox/><h2>Knowledge Library</h2>{cats.map(c=><div className="node"><div><b>{c.n}</b><small>{c.items.length} categories • {c.items.length+4} videos</small></div><ChevronRight/></div>)}<h3>Videos</h3><div className="videos">{vids.map(v=><Video key={v} t={v}/>)}</div></section>}
function Video({t}){return <div className="video"><div className="thumb"><Play/></div><b>{t}</b><small>Beginner • 12:45</small></div>}
function AI(){return <section className="screen"><Header/><h2>Ask FALTAH AI</h2><div className="chat"><p>Hello. Ask me about equipment, operation, troubleshooting, videos, or documents.</p></div>{['Explain centrifugal pump operation','Compare PSV vs PRV','Find videos about mechanical seals','Show separator fundamentals'].map(q=><button className="prompt">{q}</button>)}</section>}
function More({admin,setAdmin,pw,setPw}){return <section className="screen"><Header/><h2>More</h2>{!admin?<div className="login"><p>Admin access only</p><input placeholder="Password" type="password" value={pw} onChange={e=>setPw(e.target.value)}/><button className="primary" onClick={()=>pw==='faltah'&&setAdmin(true)}>Login</button></div>:<div><div className="node"><b>CMS</b><small>Manage videos, categories, homepage</small></div><div className="node"><b>Analytics</b><small>Admin only</small></div><div className="node"><Settings/>Settings</div><button onClick={()=>setAdmin(false)}>Logout</button></div>}</section>}
createRoot(document.getElementById('root')).render(<App/>);
